### ISSUE TITLE
Are we suppose to create a random slack token?

### ISSUE THREAD

**Issue by hungrymonkey** [Awesome-Technologies/slack-matrix-migration#2]
```
Successfully installed PyYAML-5.1 certifi-2019.11.28 chardet-3.0.4 click-7.1.1 idna-2.8 pyemojify-0.2.0 requests-2.21.0 slackdown-0.0.3 urllib3-1.24.3
/ $ cd /data
/data $ python3 migrate.py 
Traceback (most recent call last):
  File "migrate.py", line 744, in <module>
    main()
  File "migrate.py", line 671, in main
    config = test_config(yaml)
  File "migrate.py", line 65, in test_config
    if not config_yaml["slack_token"] and not yaml["skip-files"]:
KeyError: 'slack_token'
```

**Comment by awesome-michael** [comment]
I think this lacks a bit of documentation. File uploads to Slack are not included in the export. So we use a Slack token to download the files. You could configure `skip-files` to use the migration without loading files from Slack or define a Slack-Token in order to include files.
