### ISSUE TITLE
Nothing was imported

### ISSUE THREAD

**Issue by hungrymonkey** [Awesome-Technologies/slack-matrix-migration#3]
Hi,

I attempted to add a random string to `slack_user` and everything still broke. This archive was created around Jan 24.
```
python3 migrate.py 
Opening zipfile: /data/slack-export.zip
Warning: Couldn't find dms.json in archive. Skipping.
Warning: Couldn't find groups.json in archive. Skipping.
Warning: Couldn't find mpims.json in archive. Skipping.
Found channels.json in archive. Adding.
Found users.json in archive. Adding.
Admin user localpart: <adminuser>
Password: 
Registering Slack user UAAAAAAA -> @<user1>:<homeserver>.com
ERROR! Received 400 Bad Request
Unrecognized request
ERROR while registering user '@<user1>:<homeserver>.com'
Registering Slack user UAAAAAAA -> @<user2>:<homeserver>.com
ERROR! Received 400 Bad Request
Unrecognized request
ERROR while registering user '@<user2>:<homeserver>.com'
Registering Slack user UAAAAAAA -> @<user3>:<homeserver>.com
ERROR! Received 400 Bad Request
Unrecognized request
ERROR while registering user '@<user3>:<homeserver>.com'
Registering Slack user UAAAAAAA -> @<user4>:<homeserver>.com
ERROR! Received 400 Bad Request
Unrecognized request
...
[]
Traceback (most recent call last):
  File "migrate.py", line 744, in <module>
    main()
  File "migrate.py", line 695, in main
    roomlist_channels = migrate_rooms(jsonFiles["channels.json"], config)
  File "migrate.py", line 345, in migrate_rooms
    _mxCreator = userLUT[channel["creator"]]
KeyError: 'U7B77777'
```

**Comment by awesome-michael** [comment]
Looks like the script is unable to register the new users at the Synapse homeserver. The which Synapse version are you using? As this project is abandoned since Nov 2019 I assume the Synapse endpoints changed too much since then and we have to adapt the script for recent Synapse versions.
